import {
  Brain,
  Cpu,
  Database,
  FileCheck,
  FileText,
  HardDrive,
  HelpCircle,
  Lock,
  LucideIcon,
  MessageSquare,
  RefreshCw,
  Search,
  Shield,
  ShoppingCart,
  Sparkles,
  TrendingUp,
  Zap,
} from "lucide-react";

import { reviewedStories, StoryCollection } from "./reviewedStoryCatalog";

export type StorySource = "reviewed" | "restored";

export interface Story {
  id: string;
  title: string;
  description: string;
  href: string;
  icon: LucideIcon;
  color: string;
  category: string;
  collection: StoryCollection;
  source?: StorySource;
}

export const restoredUserStories: Story[] = [
  {
    id: "orchestrator-story",
    title: "The Orchestrator Story",
    description: "How AI Fabric coordinates routing, policy, provider calls, memory, and action flow.",
    href: "/docs/orchestrator_story",
    icon: Shield,
    color: "bg-blue-500",
    category: "Orchestration",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "orchestrator-story-v2",
    title: "Orchestrator Story V2",
    description: "A narrative explanation of fail-closed orchestration when an AI request becomes risky.",
    href: "/docs/orchestrator_story_v2",
    icon: Shield,
    color: "bg-blue-500",
    category: "Orchestration",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "pii-detection",
    title: "PII Detection Story",
    description: "Detect and redact sensitive text before retrieval, logging, or LLM calls.",
    href: "/docs/pii_detection",
    icon: Lock,
    color: "bg-red-500",
    category: "Privacy",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "rag-story",
    title: "The RAG Story",
    description: "Ground generated answers in retrieved application knowledge and visible evidence.",
    href: "/docs/rag_story",
    icon: Search,
    color: "bg-purple-500",
    category: "RAG",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "rag-story-v2",
    title: "RAG Story V2",
    description: "A support scenario showing why retrieved evidence matters before generation.",
    href: "/docs/rag_story_v2",
    icon: Search,
    color: "bg-purple-500",
    category: "RAG",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "rag-story-v3",
    title: "RAG Story V3",
    description: "The richest RAG walkthrough: support answers grounded in knowledge-base evidence.",
    href: "/docs/rag_story_v3",
    icon: Search,
    color: "bg-purple-500",
    category: "RAG",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "behavior-story",
    title: "The Behavior Story",
    description: "Use application events as evidence for behavior analysis and follow-up decisions.",
    href: "/docs/behavior_story",
    icon: TrendingUp,
    color: "bg-green-500",
    category: "Behavior",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "behavior-story-v2",
    title: "Behavior Story V2",
    description: "A customer journey showing how raw events become behavior insight.",
    href: "/docs/behavior_story_v2",
    icon: TrendingUp,
    color: "bg-green-500",
    category: "Behavior",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "indexing-story",
    title: "The Indexing Story",
    description: "Keep AI-searchable evidence aligned with changing application data.",
    href: "/docs/indexing_story",
    icon: Database,
    color: "bg-cyan-500",
    category: "Indexing",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "indexing-story-v2",
    title: "Indexing Story V2",
    description: "A high-change-data narrative about choosing sync, async, or batch indexing.",
    href: "/docs/indexing_story_v2",
    icon: Database,
    color: "bg-cyan-500",
    category: "Indexing",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "custom-storage-indexing",
    title: "Custom Storage Indexing",
    description: "Index data from non-standard storage while preserving app-owned source of truth.",
    href: "/docs/custom_storage_indexing",
    icon: HardDrive,
    color: "bg-indigo-500",
    category: "Indexing",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "storage-story",
    title: "The Storage Story",
    description: "Choose storage strategies for AI evidence, metadata, and lifecycle operations.",
    href: "/docs/storage_story",
    icon: HardDrive,
    color: "bg-indigo-500",
    category: "Storage",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "storage-story-v2",
    title: "Storage Story V2",
    description: "A growth story about moving from simple storage to deliberate AI data strategy.",
    href: "/docs/storage_story_v2",
    icon: HardDrive,
    color: "bg-indigo-500",
    category: "Storage",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "intent-story",
    title: "The Intent Extraction Story",
    description: "Turn natural language into bounded intent that the Java app can validate.",
    href: "/docs/intent_story",
    icon: MessageSquare,
    color: "bg-pink-500",
    category: "Actions",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "intent-story-v2",
    title: "Intent Story V2",
    description: "Interactive governed-action flow with confirmation before app-owned execution.",
    href: "/docs/intent_story_v2",
    icon: MessageSquare,
    color: "bg-pink-500",
    category: "Actions",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "migration-story",
    title: "The Migration Story",
    description: "Plan AI indexing migrations with explicit stages, checks, and rollback thinking.",
    href: "/docs/migration_story",
    icon: RefreshCw,
    color: "bg-orange-500",
    category: "Operations",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "migration-story-v2",
    title: "Migration Story V2",
    description: "A narrative migration walkthrough focused on verification rather than hero claims.",
    href: "/docs/migration_story_v2",
    icon: RefreshCw,
    color: "bg-orange-500",
    category: "Operations",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "access-policy-story",
    title: "The Access Policy Story",
    description: "Keep AI retrieval and actions inside app-owned authorization boundaries.",
    href: "/docs/access_policy_story",
    icon: Shield,
    color: "bg-red-500",
    category: "Security",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "access-policy-story-v2",
    title: "Access Policy Story V2",
    description: "A security-audit narrative about fail-closed access decisions around AI flows.",
    href: "/docs/access_policy_story_v2",
    icon: Shield,
    color: "bg-red-500",
    category: "Security",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "pii-detection-story-v1",
    title: "PII Detection Story V1",
    description: "Build privacy-aware request handling with detection, redaction, and audit evidence.",
    href: "/docs/pii_detection_story_v1",
    icon: Lock,
    color: "bg-red-500",
    category: "Privacy",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "pii-detection-story-v2",
    title: "PII Detection Story V2",
    description: "A privacy-audit narrative showing why AI paths need sensitive-data controls.",
    href: "/docs/pii_detection_story_v2",
    icon: Lock,
    color: "bg-red-500",
    category: "Privacy",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "relationship-query-story-v2",
    title: "Relationship Query Story V2",
    description: "Answer relational-data questions through explicit schema and policy boundaries.",
    href: "/docs/relationship_query_story_v2",
    icon: Brain,
    color: "bg-violet-500",
    category: "Query",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "openai-provider-story",
    title: "OpenAI Provider Story",
    description: "Use AI Fabric's Spring AI-backed provider wiring for OpenAI model calls.",
    href: "/docs/openai_provider_story",
    icon: Zap,
    color: "bg-yellow-500",
    category: "Provider",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "openai-provider-story-v2",
    title: "OpenAI Provider Story V2",
    description: "A provider wiring narrative showing how AI Fabric keeps policy above model calls.",
    href: "/docs/openai_provider_story_v2",
    icon: Zap,
    color: "bg-yellow-500",
    category: "Provider",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "onnx-provider-story",
    title: "ONNX Provider Story",
    description: "Use local embedding options when the app needs local inference or offline behavior.",
    href: "/docs/onnx_provider_story",
    icon: Cpu,
    color: "bg-cyan-500",
    category: "Provider",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "onnx-provider-story-v2",
    title: "ONNX Provider Story V2",
    description: "A local-embedding narrative focused on control, tradeoffs, and verification.",
    href: "/docs/onnx_provider_story_v2",
    icon: Cpu,
    color: "bg-cyan-500",
    category: "Provider",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "audit-capabilities-story",
    title: "Audit Capabilities Story",
    description: "Capture request, retrieval, action, and diagnostic evidence for AI workflows.",
    href: "/docs/audit_capabilities_story",
    icon: FileCheck,
    color: "bg-emerald-500",
    category: "Audit",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "audit-capabilities-story-v2",
    title: "Audit Capabilities Story V2",
    description: "A narrative audit walkthrough for proving what happened in an AI request path.",
    href: "/docs/audit_capabilities_story_v2",
    icon: FileCheck,
    color: "bg-emerald-500",
    category: "Audit",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "cleanup-capabilities-story",
    title: "Cleanup Capabilities Story",
    description: "Design cleanup flows for AI data, vectors, and lifecycle metadata.",
    href: "/docs/cleanup_capabilities_story",
    icon: Sparkles,
    color: "bg-teal-500",
    category: "Lifecycle",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "cleanup-capabilities-story-v2",
    title: "Cleanup Capabilities Story V2",
    description: "A data-growth narrative about keeping AI indexes and metadata intentional.",
    href: "/docs/cleanup_capabilities_story_v2",
    icon: Sparkles,
    color: "bg-teal-500",
    category: "Lifecycle",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "retention-capabilities-story",
    title: "Retention Capabilities Story",
    description: "Use pluggable retention policies as part of app-owned data lifecycle controls.",
    href: "/docs/retention_capabilities_story",
    icon: FileText,
    color: "bg-slate-500",
    category: "Lifecycle",
    collection: "user-stories",
    source: "restored",
  },
  {
    id: "retention-capabilities-story-v2",
    title: "Retention Capabilities Story V2",
    description: "A retention-policy narrative about audit evidence and explicit lifecycle rules.",
    href: "/docs/retention_capabilities_story_v2",
    icon: FileText,
    color: "bg-slate-500",
    category: "Lifecycle",
    collection: "user-stories",
    source: "restored",
  },
];

export const restoredRealApiStories: Story[] = [
  {
    id: "ecommerce-product-discovery",
    title: "E-Commerce Product Discovery",
    description: "A commerce story for semantic product discovery, cart actions, and RAG evidence.",
    href: "/docs/ecommerce-product-discovery-story",
    icon: ShoppingCart,
    color: "bg-blue-500",
    category: "Commerce",
    collection: "real-api-stories",
    source: "restored",
  },
  {
    id: "financial-fraud-detection",
    title: "Financial Fraud Detection",
    description: "A relationship-query story for suspicious flows and governed financial investigation.",
    href: "/docs/financial-fraud-detection-story",
    icon: Shield,
    color: "bg-green-500",
    category: "Finance",
    collection: "real-api-stories",
    source: "restored",
  },
  {
    id: "law-firm-document",
    title: "Law Firm Document Management",
    description: "A legal-document discovery story for retrieval, evidence, and controlled search.",
    href: "/docs/law-firm-document-story",
    icon: FileText,
    color: "bg-purple-500",
    category: "Legal",
    collection: "real-api-stories",
    source: "restored",
  },
  {
    id: "pii-detection-edge",
    title: "PII Detection Edge Spectrum",
    description: "A privacy testing story for edge-case PII detection and redaction behavior.",
    href: "/docs/pii-detection-edge-story",
    icon: Lock,
    color: "bg-red-500",
    category: "Privacy",
    collection: "real-api-stories",
    source: "restored",
  },
  {
    id: "smart-suggestions",
    title: "Smart Suggestions",
    description: "A UX story for AI-proposed next steps with confidence and visible context.",
    href: "/docs/smart-suggestions-story",
    icon: Sparkles,
    color: "bg-yellow-500",
    category: "UX",
    collection: "real-api-stories",
    source: "restored",
  },
  {
    id: "onnx-fallback",
    title: "ONNX Fallback Readiness",
    description: "A provider-resilience story for local embeddings and fallback verification.",
    href: "/docs/onnx-fallback-story",
    icon: Cpu,
    color: "bg-cyan-500",
    category: "Provider",
    collection: "real-api-stories",
    source: "restored",
  },
  {
    id: "real-ai-embedding",
    title: "Real AI Embedding Generation",
    description: "A semantic-search story showing product records becoming searchable vectors.",
    href: "/docs/real-ai-embedding-story",
    icon: Zap,
    color: "bg-orange-500",
    category: "Embeddings",
    collection: "real-api-stories",
    source: "restored",
  },
  {
    id: "vector-lifecycle",
    title: "Vector Lifecycle Management",
    description: "A vector lifecycle story for create, remove, clear, reseed, diagnostics, and audit evidence.",
    href: "/docs/vector-lifecycle-story",
    icon: RefreshCw,
    color: "bg-indigo-500",
    category: "Vector",
    collection: "real-api-stories",
    source: "restored",
  },
];

export const restoredStoryLibrary: Story[] = [...restoredUserStories, ...restoredRealApiStories];

const reviewedNavigationStories: Story[] = reviewedStories.map((story) => ({
  id: story.id,
  title: story.title,
  description: story.description,
  href: story.href,
  icon: story.icon,
  color: story.color,
  category: story.category,
  collection: story.collection,
  source: "reviewed",
}));

const reviewedHrefs = new Set(reviewedNavigationStories.map((story) => story.href));

export const allStories: Story[] = [
  ...reviewedNavigationStories,
  ...restoredStoryLibrary.filter((story) => !reviewedHrefs.has(story.href)),
];

export function getStoryByHref(href: string): Story | undefined {
  return allStories.find((story) => story.href === href);
}

export function getStoryNavigation(currentHref: string): {
  previous: Story | null;
  next: Story | null;
  currentIndex: number;
  totalStories: number;
} {
  const currentIndex = allStories.findIndex((story) => story.href === currentHref);

  if (currentIndex === -1) {
    return { previous: null, next: null, currentIndex: -1, totalStories: allStories.length };
  }

  return {
    previous: currentIndex > 0 ? allStories[currentIndex - 1] : null,
    next: currentIndex < allStories.length - 1 ? allStories[currentIndex + 1] : null,
    currentIndex,
    totalStories: allStories.length,
  };
}

export function getStoriesByCollection(collection: StoryCollection): Story[] {
  return allStories.filter((story) => story.collection === collection);
}

export function getRandomStories(currentHref: string, count: number = 3): Story[] {
  const otherStories = allStories.filter((story) => story.href !== currentHref);
  const shuffled = [...otherStories].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export const fallbackStory: Story = {
  id: "story-not-found",
  title: "All Stories",
  description: "Return to the restored AI Fabric story library.",
  href: "/docs/user-stories",
  icon: HelpCircle,
  color: "bg-slate-500",
  category: "Stories",
  collection: "user-stories",
  source: "restored",
};
