export { ProductsTab } from "./ProductsTab";
export { OrdersTab } from "./OrdersTab";
export { PoliciesTab } from "./PoliciesTab";
export { ReviewsTab } from "./ReviewsTab";
export { CouponsTab } from "./CouponsTab";
export { CartTab } from "./CartTab";
export { SupportTab } from "./SupportTab";
export { ApiTab } from "./ApiTab";
export { VerificationTab } from "./VerificationTab";
