export type DemoBackendArchitectureTone = "live" | "candidate" | "concept";

export interface DemoBackendArchitectureConfig {
  title: string;
  status: string;
  tone: DemoBackendArchitectureTone;
  backendApp: string;
  publicBackend?: string;
  uiRoutes: string[];
  summary: string;
  diagram?: DemoArchitectureStage[];
  developer?: DemoDeveloperDetails;
  dependencies: string[];
  modules: string[];
  aiSurface: string[];
  providers: string[];
  flow: string[];
  operationalProofs?: string[];
}

export type DemoArchitectureStageTone = "ui" | "api" | "framework" | "rag" | "provider" | "storage" | "guard";

export interface DemoArchitectureStage {
  title: string;
  subtitle: string;
  tone: DemoArchitectureStageTone;
  items: string[];
}

export interface DemoDeveloperDetails {
  sourcePath: string;
  dockerfilePath: string;
  healthEndpoint: string;
  primaryEndpoints: string[];
  localRun: string[];
  envVars: string[];
  codeHotspots: string[];
}

export const demoBackendArchitectures = {
  mcpOperations: {
    title: "AI Fabric MCP Operations backend",
    status: "Live remote MCP backend",
    tone: "live",
    backendApp: "examples/real-apps/mcp-operations-assistant",
    publicBackend: "https://ai-fabric-mcp-operations.46.224.145.148.sslip.io",
    uiRoutes: ["/demos/ai-fabric-mcp-operations"],
    summary:
      "A two-service Spring Boot proof in which an AI Fabric specialist calls an authenticated remote MCP server while the application retains identity, tool policy, trusted arguments, confirmation, receipts, replay protection, and safe result projection.",
    diagram: [
      {
        title: "Operations UI",
        subtitle: "Session-isolated browser",
        tone: "ui",
        items: ["Newest-message-only chat", "Service inventory and source state", "Confirmation and safe audit timeline"],
      },
      {
        title: "Assistant API",
        subtitle: "Application-owned trust boundary",
        tone: "api",
        items: ["Opaque mcp-demo identity", "Backend-selected service and revision", "No browser authority fields"],
      },
      {
        title: "AI Fabric runtime",
        subtitle: "Specialist and action governance",
        tone: "framework",
        items: ["mcp-operations-specialist@1", "Exact action catalog", "Durable confirmation receipt and replay"],
      },
      {
        title: "Spring AI MCP bridge",
        subtitle: "Authenticated Streamable HTTP",
        tone: "guard",
        items: ["Exact serverRef", "Bounded result mapping", "No local fallback in live profile"],
      },
      {
        title: "Reference MCP server",
        subtitle: "Narrow sandbox system of record",
        tone: "storage",
        items: ["Three allowlisted tools", "Optimistic revision check", "Persistent isolated service state"],
      },
    ],
    developer: {
      sourcePath: "examples/real-apps/mcp-operations-assistant",
      dockerfilePath: "examples/real-apps/mcp-operations-assistant/Dockerfile",
      healthEndpoint: "GET /api/demo/health",
      primaryEndpoints: [
        "POST /api/mcp-ops/sessions",
        "GET /api/mcp-ops/sessions/{id}/state",
        "POST /api/mcp-ops/sessions/{id}/chat",
        "POST /api/mcp-ops/sessions/{id}/actions/decide",
        "POST /api/mcp-ops/sessions/{id}/binding-canary",
        "GET /api/mcp-ops/connection",
      ],
      localRun: [
        "Build and start mcp-operations-reference-server on port 8106 with MCP_SERVER_API_KEY.",
        "Run mcp-operations-assistant on port 8100 with the matching protected key.",
        "Use the smoke profile plus app.mcp-operations.executor=remote to prove the real protocol without an LLM key.",
        "Use OpenAI only for the live specialist scenarios; failures remain visible.",
      ],
      envVars: [
        "OPENAI_ENABLED",
        "OPENAI_API_KEY",
        "OPENAI_MODEL",
        "MCP_OPERATIONS_SERVER_URL",
        "MCP_OPERATIONS_SERVER_API_KEY",
        "AI_EXECUTION_RECEIPT_ENCRYPTION_SECRET",
        "AI_EXECUTION_RECEIPT_FINGERPRINT_SECRET",
        "SPRING_DATASOURCE_URL",
        "CORS_ALLOWED_ORIGINS",
      ],
      codeHotspots: [
        "src/main/resources/ai-actions.yml",
        "src/main/resources/ai-specialists/mcp-operations-specialist.yml",
        "config/McpClientConfiguration.java",
        "specialist/McpOperationsExecutionService.java",
        "service/AuditedMcpActionExecutor.java",
        "../mcp-operations-reference-server/service/SandboxOperationsTools.java",
      ],
    },
    dependencies: [
      "Spring Boot Web, Data JPA, Validation, Actuator, H2/PostgreSQL, Spring AI MCP client, and smoke-support.",
      "The companion reference server uses Spring AI MCP server WebMVC and an independent persistent data source.",
    ],
    modules: [
      "ai-fabric-starter",
      "ai-fabric-execution",
      "ai-fabric-chat-session",
      "ai-fabric-actions-connector",
      "ai-fabric-provider-spring-ai",
    ],
    aiSurface: [
      "A typed specialist can request only the three action-catalog tools exposed in its exact manifest version.",
      "Read calls provide grounding while the restart tool produces an encrypted durable proposal instead of an immediate side effect.",
      "The application builds sandbox identity, selected service, optimistic revision, scopes, tenant, and deployment from trusted backend state.",
      "The connector resolves the exact remote server name and rejects an unresolved server even if another client exposes the same tool name.",
    ],
    providers: [
      "OpenAI provides live structured specialist reasoning through ai-fabric-provider-spring-ai.",
      "Spring AI provides the Streamable HTTP MCP client and server infrastructure.",
      "JDBC stores assistant sessions, chat turns, tool audits, action receipts, and remote sandbox state.",
    ],
    flow: [
      "The browser creates an opaque demo session and selects one allowlisted service.",
      "The backend reads current revision from the authenticated remote MCP server before specialist execution.",
      "AI Fabric invokes approved read tools or creates a confirmation receipt for the restart tool.",
      "An authorized decision executes the exact receipt once, maps a safe outcome, and returns current source state.",
      "The UI shows server, tool, access mode, duration, result state, and the fail-closed duplicate-server canary without exposing credentials or trusted arguments.",
    ],
    operationalProofs: [
      "Restart proposals are stored as encrypted JDBC receipts; confirming a terminal receipt returns its stored outcome instead of invoking the remote tool twice.",
      "The companion MCP service persists isolated source state, and remote outages remain visible because the live profile has no local tool fallback.",
    ],
  },
  incidentInvestigation: {
    title: "Incident Investigation Room backend",
    status: "Live multi-specialist backend",
    tone: "live",
    backendApp: "examples/real-apps/incident-investigation-room",
    publicBackend: "https://ai-fabric-incident-investigation.46.224.145.148.sslip.io",
    uiRoutes: ["/demos/ai-fabric-incident-investigation"],
    summary:
      "A Spring Boot proof where OpenAI routes each incident to an exact-version specialist, the specialist selects approved operational read actions and runbook evidence, and AI Fabric validates every citation before plans, transitions, or conversation results reach the UI.",
    diagram: [
      {
        title: "Investigation UI",
        subtitle: "Session-isolated operations lab",
        tone: "ui",
        items: ["Authorized event workspace", "Five-stage decision trace", "Plan, transition, and conversation labs"],
      },
      {
        title: "Incident API",
        subtitle: "Server-owned execution context",
        tone: "api",
        items: ["Opaque demo sessions", "Trusted tenant and deployment scope", "Safe typed projections"],
      },
      {
        title: "Execution runtime",
        subtitle: "Exact v2 specialists and fixed plans",
        tone: "framework",
        items: ["Model-selected specialist", "Specialist-selected read actions", "Sequential or parallel fan-out"],
      },
      {
        title: "Operational evidence",
        subtitle: "Bounded sources plus scoped RAG",
        tone: "provider",
        items: ["Metrics, alerts, deployments, approvals", "Lucene incident runbooks", "Realistic excluded distractors"],
      },
      {
        title: "Transition boundary",
        subtitle: "One specialist hop only",
        tone: "guard",
        items: ["Delegation lineage", "Handoff lineage", "Second-transition rejection canary"],
      },
      {
        title: "Validation and memory",
        subtitle: "Application-enforced boundaries",
        tone: "guard",
        items: ["Citation and revision checks", "Bounded chat snapshots", "H2/PostgreSQL session storage"],
      },
    ],
    developer: {
      sourcePath: "examples/real-apps/incident-investigation-room",
      dockerfilePath: "examples/real-apps/incident-investigation-room/Dockerfile",
      healthEndpoint: "GET /api/demo/health",
      primaryEndpoints: [
        "POST /api/incidents/sessions",
        "POST /api/incidents/sessions/{id}/plans/{sequential|parallel}",
        "POST /api/incidents/sessions/{id}/compare",
        "POST /api/incidents/sessions/{id}/delegations",
        "POST /api/incidents/sessions/{id}/handoffs",
        "POST /api/incidents/sessions/{id}/manager/turns",
        "GET /api/incidents/sessions/{id}",
      ],
      localRun: [
        "mvn -f examples/real-apps/pom.xml -pl incident-investigation-room -am test",
        "Use the smoke profile for deterministic keyless plan, transition, and memory verification.",
        "Set OPENAI_ENABLED=true and OPENAI_API_KEY for live specialist intelligence.",
        "Run IncidentInvestigationRealApiIntegrationTest to prove real routing, read-action selection, scoped RAG, plans, and backend memory.",
      ],
      envVars: [
        "PORT",
        "OPENAI_ENABLED",
        "OPENAI_API_KEY",
        "OPENAI_MODEL",
        "APP_DATA_DIR",
        "CORS_ALLOWED_ORIGINS",
      ],
      codeHotspots: [
        "execution/IncidentPlans.java",
        "execution/IncidentSpecialists.java",
        "action/IncidentReadActions.java",
        "service/InMemoryIncidentEventRepository.java",
        "service/IncidentRunbookIndexService.java",
        "service/IncidentExecutionService.java",
        "service/IncidentConversationService.java",
        "web/IncidentController.java",
        "src/main/resources/ai-specialists",
      ],
    },
    dependencies: [
      "Spring Boot Web, Data JPA, Validation, Actuator, H2, PostgreSQL, Lucene, and smoke-support.",
      "Stable application storage preserves backend conversation state; the deterministic event repository models an external operational source while fixed plan executions remain explicitly ephemeral.",
    ],
    modules: [
      "ai-fabric-starter",
      "ai-fabric-execution",
      "ai-fabric-chat-session",
      "ai-fabric-rag",
      "ai-fabric-vector-lucene",
      "ai-fabric-provider-spring-ai",
    ],
    aiSurface: [
      "Exact-version v2 manifests define typed service-health, change-risk, intake, and conversation-manager contracts while v1 definitions remain available.",
      "Each worker can request only its allowlisted grounding-eligible READ actions; trusted incident, tenant, deployment, and revision values come from the backend.",
      "The change specialist combines deployment and approval actions with tenant-scoped incident-runbook RAG.",
      "Fixed plans run the same independent branches sequentially or in parallel under ALL_REQUIRED fan-in.",
      "The application aggregator validates event citations, runbook citations, source revision, tenant, and deployment before returning an assessment.",
      "Delegation and handoff expose safe lineage while runtime policy rejects a second specialist transition.",
    ],
    providers: [
      "OpenAI through ai-fabric-provider-spring-ai in the live profile.",
      "A deterministic smoke-only AIProvider validates packaged runtime contracts without hiding live provider failures.",
      "Lucene stores six scoped runbook documents; JDBC chat-session storage preserves bounded conversation history.",
    ],
    flow: [
      "The browser creates an opaque session bound to one authorized incident workspace and sends no trusted identity fields.",
      "OpenAI intake sees boundary identifiers, selects an exact worker, and cannot read the full event payloads.",
      "The worker chooses from its allowlisted READ actions; the backend resolves trusted scope and returns authorized candidates containing realistic distractors.",
      "OpenAI selects and cites the relevant candidates. The change worker can also retrieve a scoped runbook through AI Fabric RAG.",
      "ALL_REQUIRED fan-in withholds partial output if either branch fails.",
      "The application validates citation ids, source revision, tenant, deployment, action provenance, and runbook scope before projecting the final assessment.",
      "Conversation turns send only the newest message while the backend supplies bounded prior context and replay state.",
    ],
    operationalProofs: [
      "Backend-owned conversation snapshots survive application restart when the deployed JDBC store is retained.",
      "Fixed plan runs are intentionally ephemeral; the UI labels their timeline and does not imply restart recovery for plan branches.",
      "The health contract reports eight exact specialist versions, four plans, four read actions, runbook readiness, provider state, and storage posture.",
      "The real-provider suite proves direct and generated scoped RAG, both specialist routes, parallel fan-out, and follow-up memory with no hidden model fallback.",
    ],
  },
  agenticActionResolver: {
    title: "Agentic AI Action Resolver backend",
    status: "Live specialist and review backend",
    tone: "live",
    backendApp: "examples/real-apps/agentic-ai-action-resolver",
    publicBackend: "https://ai-fabric-agentic-action-resolver.46.224.145.148.sslip.io",
    uiRoutes: [
      "/demos/ai-fabric-agentic-action-resolver",
      "/demos/ai-fabric-agentic-action-resolver/review",
    ],
    summary:
      "A Spring Boot reference application for exact-version specialist execution, backend-owned conversation, typed input waits, fixed composition, governed write receipts, replay protection, and durable human review.",
    diagram: [
      {
        title: "Resolver and review UIs",
        subtitle: "Session-isolated browser",
        tone: "ui",
        items: ["Newest-message-only chat", "Typed input and confirmation cards", "Session-bound reviewer desk"],
      },
      {
        title: "Public demo facade",
        subtitle: "Spring Boot API",
        tone: "api",
        items: ["Opaque demo sessions", "Server-owned identity and scopes", "Safe result projections"],
      },
      {
        title: "Specialist runtime",
        subtitle: "AI Fabric execution",
        tone: "framework",
        items: ["Manifest compilation", "Typed adapters and validators", "Wait, plan, delegation, and handoff"],
      },
      {
        title: "Governed continuation",
        subtitle: "Durable JDBC state",
        tone: "guard",
        items: ["Encrypted action receipts", "Idempotent replay", "Durable review tasks and decisions"],
      },
      {
        title: "Evidence and providers",
        subtitle: "Approved runtime backing",
        tone: "provider",
        items: ["OpenAI generation", "Lucene policy and plan vectors", "H2/PostgreSQL domain and execution state"],
      },
    ],
    developer: {
      sourcePath: "examples/real-apps/agentic-ai-action-resolver",
      dockerfilePath: "examples/real-apps/agentic-ai-action-resolver/Dockerfile",
      healthEndpoint: "GET /api/demo/health",
      primaryEndpoints: [
        "POST /api/agentic-resolver/sessions",
        "POST /api/agentic-resolver/chat",
        "POST /api/agentic-resolver/input/resume",
        "POST /api/agentic-resolver/actions/decide",
        "POST /api/agentic-resolver/reviews/support-credit",
        "POST /api/agentic-resolver/demo-reviews/sessions",
        "GET /api/agentic-resolver/demo-reviews",
        "POST /api/agentic-resolver/events/payment-verification-failed",
      ],
      localRun: [
        "mvn -f examples/real-apps/pom.xml -pl agentic-ai-action-resolver -am package",
        "Use the smoke profile for deterministic keyless contract verification.",
        "Enable reviews with stable receipt/review secrets and distinct server-side reviewer keys.",
        "Set OPENAI_ENABLED=true and OPENAI_API_KEY for live specialist intelligence.",
      ],
      envVars: [
        "PORT",
        "OPENAI_ENABLED",
        "OPENAI_API_KEY",
        "OPENAI_MODEL",
        "AI_EXECUTION_RECEIPT_ENCRYPTION_SECRET",
        "AI_EXECUTION_RECEIPT_FINGERPRINT_SECRET",
        "AI_EXECUTION_REVIEW_ENCRYPTION_SECRET",
        "AI_EXECUTION_REVIEW_FINGERPRINT_SECRET",
        "APP_REVIEWER_API_KEY",
        "APP_SENIOR_REVIEWER_API_KEY",
        "CORS_ALLOWED_ORIGINS",
      ],
      codeHotspots: [
        "agentic/AccountResolverSpecialists.java",
        "agentic/AgenticResolverExecutionService.java",
        "agentic/AgenticResolverSessionService.java",
        "agentic/review/SupportCreditReviewService.java",
        "agentic/review/DemoReviewerSessionService.java",
        "controller/AgenticResolverController.java",
        "controller/DemoReviewController.java",
        "src/main/resources/META-INF/ai-fabric/specialists",
      ],
    },
    dependencies: [
      "Spring Boot Web, Data JPA, Validation, Actuator, H2, PostgreSQL, and smoke-support.",
      "Stable hosted storage and application-managed secrets are required for restart-safe receipts and reviews.",
    ],
    modules: [
      "ai-fabric-starter",
      "ai-fabric-execution",
      "ai-fabric-chat-session",
      "ai-fabric-rag",
      "ai-fabric-vector-lucene",
      "ai-fabric-provider-spring-ai",
    ],
    aiSurface: [
      "Versioned specialist manifests bind typed input/output schemas, approved vectors, actions, and execution profiles.",
      "Backend-owned trusted context fixes principal, subject, tenant, deployment, and scopes before retrieval or execution.",
      "Typed input waits expose a safe response schema and resume the original invocation without browser-supplied authority.",
      "Governed writes remain encrypted in receipts until confirmation or policy-authorized human review.",
    ],
    providers: [
      "OpenAI through ai-fabric-provider-spring-ai for live specialist reasoning.",
      "Lucene for account policy and subscription-plan evidence.",
      "JDBC repositories for action receipts, durable executions, review tasks, and application sessions.",
    ],
    flow: [
      "The browser creates an opaque demo session and sends only the newest user message.",
      "The backend resolves account subject, exact specialist, capabilities, provider, and approved evidence sources.",
      "AI Fabric validates typed output and either returns information, a bounded input wait, or a safe action proposal.",
      "Confirmation executes the linked receipt once and reconciles the projected outcome with application state.",
      "Human-review proposals are durably dispatched; short-lived reviewer credentials expose only tasks bound to the same demo session.",
    ],
    operationalProofs: [
      "Encrypted action receipts and review tasks survive controlled restarts when the configured JDBC store and secrets remain stable.",
      "Terminal receipt replay returns the stored outcome without repeating the account mutation; typed input waits remain explicitly ephemeral.",
    ],
  },
  deploymentKnowledgeGuard: {
    title: "Deployment Knowledge Guard backend",
    status: "Live trusted retrieval backend",
    tone: "live",
    backendApp: "examples/real-apps/deployment-knowledge-guard",
    publicBackend: "https://ai-fabric-deployment-knowledge-guard.46.224.145.148.sslip.io",
    uiRoutes: ["/demos/ai-fabric-deployment-knowledge-guard"],
    summary:
      "A read-only operations specialist that binds server-approved tenant and deployment identity into AI Fabric retrieval, validates structured citations, and rejects evidence outside the active source catalog.",
    diagram: [
      {
        title: "Operator UI",
        subtitle: "Opaque demo session",
        tone: "ui",
        items: ["Approved context picker", "Operational questions", "Leakage canaries"],
      },
      {
        title: "Demo facade",
        subtitle: "Server-owned boundary",
        tone: "api",
        items: ["Context ID resolution", "Trusted principal and subject", "Safe evidence projection"],
      },
      {
        title: "Specialist runtime",
        subtitle: "deployment-knowledge-reader@1",
        tone: "framework",
        items: ["Manifest schema", "Structured generation", "Citation validator"],
      },
      {
        title: "Scoped retrieval",
        subtitle: "Verified metadata filters",
        tone: "guard",
        items: ["Tenant exact match", "Deployment exact match", "Caller spoof overwrite"],
      },
      {
        title: "Evidence and intelligence",
        subtitle: "Provider-backed runtime",
        tone: "provider",
        items: ["OpenAI generation and embeddings", "Lucene vectors", "Overlapping document titles"],
      },
    ],
    developer: {
      sourcePath: "examples/real-apps/deployment-knowledge-guard",
      dockerfilePath: "examples/real-apps/deployment-knowledge-guard/Dockerfile",
      healthEndpoint: "GET /api/demo/health",
      primaryEndpoints: [
        "POST /api/deployment-guard/sessions",
        "PUT /api/deployment-guard/sessions/current/contexts/{contextId}",
        "POST /api/deployment-guard/query",
        "POST /api/deployment-guard/canaries/{type}",
        "GET /api/deployment-guard/evidence",
      ],
      localRun: [
        "mvn -f examples/real-apps/pom.xml -pl deployment-knowledge-guard -am test",
        "Use the smoke profile for keyless Lucene boundary verification.",
        "Set OPENAI_ENABLED=true and OPENAI_API_KEY for live structured specialist answers.",
      ],
      envVars: [
        "PORT",
        "OPENAI_ENABLED",
        "OPENAI_API_KEY",
        "OPENAI_MODEL",
        "OPENAI_EMBEDDING_MODEL",
        "OPENAI_EMBEDDING_DIMENSIONS",
        "CORS_ALLOWED_ORIGINS",
      ],
      codeHotspots: [
        "specialist/DeploymentKnowledgeResult.java",
        "service/DeploymentKnowledgeExecutionService.java",
        "service/DeploymentKnowledgeIndexService.java",
        "domain/DeploymentKnowledgeCatalog.java",
        "src/main/resources/ai-specialists/deployment-knowledge-reader.yml",
      ],
    },
    dependencies: [
      "Spring Boot Web, Validation, Actuator, smoke-support, and AI Fabric 0.5.3 modules.",
      "No application database is required; Lucene stores the immutable demo evidence vectors.",
    ],
    modules: [
      "ai-fabric-starter",
      "ai-fabric-execution",
      "ai-fabric-rag",
      "ai-fabric-vector-lucene",
      "ai-fabric-provider-spring-ai",
    ],
    aiSurface: [
      "The application supplies identity through TrustedExecutionContext; public query JSON contains only the question.",
      "AI Fabric overwrites caller tenant/deployment values and applies trusted fields as vector metadata filters.",
      "A final validator accepts only evidence IDs retrieved for the current invocation.",
      "The application rechecks every projected evidence ID against its server-owned context catalog.",
    ],
    providers: [
      "OpenAI provides live generation and embeddings through ai-fabric-provider-spring-ai.",
      "Lucene performs exact tenant/deployment metadata filtering before similarity ranking.",
      "Smoke providers prove the same vector boundary without external keys.",
    ],
    flow: [
      "Create an opaque session and choose one server-approved context ID.",
      "Resolve tenant/deployment identity on the backend and construct TrustedExecutionContext.",
      "Invoke deployment-knowledge-reader@1 with only the operator question as public input.",
      "Retrieve filtered evidence, generate typed output, validate citations, and project safe evidence.",
      "Run cross-tenant, cross-deployment, and identity-spoof canaries without changing the trusted boundary.",
    ],
  },
  liveDataSync: {
    title: "AI Fabric Live Data Sync backend",
    status: "Live backend-backed demo",
    tone: "live",
    backendApp: "examples/real-apps/ai-fabric-live-data-sync",
    publicBackend: "https://ai-fabric-live-data-sync.46.224.145.148.sslip.io",
    uiRoutes: ["/demos/ai-fabric-live-data-sync"],
    summary:
      "A Spring Boot application that owns ordinary JPA rows and lets AI Fabric annotations keep product, policy, and support-guide vectors synchronized for evidence-grounded retrieval.",
    diagram: [
      {
        title: "React proof UI",
        subtitle: "ai-fabric.dev",
        tone: "ui",
        items: ["Create, edit, and delete source rows", "Inspect durable work receipts", "Reusable AI Fabric Chat UI"],
      },
      {
        title: "Domain API",
        subtitle: "Spring Boot + JPA",
        tone: "api",
        items: ["Session-isolated workspaces", "Normal entity service calls", "Safe indexing status projection"],
      },
      {
        title: "Annotation lifecycle",
        subtitle: "AI Fabric indexing",
        tone: "framework",
        items: ["@AICapable entity contract", "@AISearchable + @AIContext extraction", "@AIProcess plus explicit receipt path"],
      },
      {
        title: "Evidence retrieval",
        subtitle: "RAG boundary",
        tone: "rag",
        items: ["Workspace metadata filter", "Three vector entity types", "Evidence-only LLM prompt"],
      },
      {
        title: "Providers and state",
        subtitle: "Runtime backing",
        tone: "provider",
        items: ["Spring AI OpenAI", "Lucene vectors", "H2 source and durable work state"],
      },
    ],
    developer: {
      sourcePath: "examples/real-apps/ai-fabric-live-data-sync",
      dockerfilePath: "examples/real-apps/ai-fabric-live-data-sync/Dockerfile",
      healthEndpoint: "GET /api/demo/health",
      primaryEndpoints: [
        "POST /api/live-sync/workspaces",
        "GET /api/live-sync/state",
        "POST /api/live-sync/entities/{entityType}",
        "PUT /api/live-sync/entities/{entityType}/{recordKey}",
        "DELETE /api/live-sync/entities/{entityType}/{recordKey}",
        "GET /api/live-sync/indexing-work/{workId}",
        "POST /api/live-sync/lifecycle/{scenario}/{entityType}/{recordKey}",
        "POST /api/live-sync/search",
        "POST /api/live-sync/chat",
        "POST /api/live-sync/reset",
      ],
      localRun: [
        "mvn -f examples/real-apps/pom.xml -pl ai-fabric-live-data-sync -am package",
        "Run with spring.profiles.active=smoke for a keyless lifecycle proof.",
        "Set OPENAI_ENABLED=true and an OpenAI key for live embeddings and generation.",
      ],
      envVars: [
        "PORT",
        "OPENAI_ENABLED",
        "OPENAI_API_KEY",
        "OPENAI_MODEL",
        "OPENAI_EMBEDDING_MODEL",
        "OPENAI_EMBEDDING_DIMENSIONS",
        "APP_DEMO_REQUIRE_REAL_AI",
        "CORS_ALLOWED_ORIGINS",
        "JAVA_OPTS",
      ],
      codeHotspots: [
        "domain/SyncProduct.java",
        "domain/SyncPolicy.java",
        "domain/SyncGuide.java",
        "service/SyncProductService.java",
        "service/LiveSyncSearchService.java",
        "service/LiveSyncChatService.java",
        "web/LiveSyncDemoController.java",
        "src/main/resources/ai-entity-config.yml",
      ],
    },
    dependencies: [
      "Spring Boot Web, Data JPA, Validation, Actuator, H2, and Lombok.",
      "smoke-support for build metadata and deterministic no-key verification.",
    ],
    modules: [
      "ai-fabric-starter",
      "ai-fabric-indexing",
      "ai-fabric-rag",
      "ai-fabric-vector-lucene",
      "ai-fabric-provider-spring-ai",
    ],
    aiSurface: [
      "@EnableAIInfrastructure activates AI Fabric in the Spring Boot application.",
      "@AICapable declares three synchronized entity types and their migration repositories.",
      "@AISearchable selects embedded text while @AIContext supplies filterable metadata and revision proof.",
      "@AIProcess observes create, update, and delete service results and synchronizes vectors without controller indexing calls.",
      "Receipt-required application writes use AIEntityIndexingGateway and expose only the safe IndexingWorkStatus contract.",
      "No action annotations or action modules are enabled in this demo.",
    ],
    providers: [
      "Spring AI OpenAI provides live embeddings and answer generation.",
      "Lucene stores vectors for sync-product, sync-policy, and sync-guide.",
      "H2 remains the application-owned source database.",
      "The smoke profile supplies deterministic local providers for keyless lifecycle tests only.",
    ],
    flow: [
      "The browser creates a six-hour isolated workspace containing two rows for each entity type.",
      "Seed/reset methods return annotated entities to @AIProcess; tracked public writes submit the same projected entity through AIEntityIndexingGateway.",
      "AnnotationFieldScanner builds vector content and metadata from @AISearchable and @AIContext fields.",
      "The UI reads source rows, vector records, and durable work status independently and compares source version metadata.",
      "RAG retrieval applies an exact workspaceId metadata filter before evidence enters generation.",
      "Delete returns the deleted entity to @AIProcess, which removes the corresponding vector before the UI verifies absence.",
    ],
  },
  shopping: {
    title: "AI Shopping Experience backend",
    status: "Live backend-backed demo",
    tone: "live",
    backendApp: "examples/real-apps/chat-capabilities-demo",
    publicBackend: "https://ai-fabric-chat-capabilities-demo.46.224.145.148.sslip.io",
    uiRoutes: ["/demos/ai-shopping-experience", "/demos/ai-fabric-framework"],
    summary:
      "A Spring Boot commerce runtime that owns product/cart/order APIs and uses AI Fabric for chat orchestration, staged RAG readiness, local actions, confirmations, and runtime data sync.",
    diagram: [
      {
        title: "React demo UI",
        subtitle: "ai-fabric.dev",
        tone: "ui",
        items: ["RAG journey controls", "Commerce tabs and cart", "Chat widget positions"],
      },
      {
        title: "Commerce API",
        subtitle: "Spring Boot app",
        tone: "api",
        items: ["/api/chat/query", "/api/demo/stages/{stage}", "/api/products and /api/carts"],
      },
      {
        title: "AI Fabric runtime",
        subtitle: "Curated commerce",
        tone: "framework",
        items: ["Mode resolver", "Chat-session memory", "Intent, actions, confirmations"],
      },
      {
        title: "RAG and indexing",
        subtitle: "Evidence pipeline",
        tone: "rag",
        items: ["@AICapable products, policies, reviews", "@AIProcess data sync", "Lucene vector spaces"],
      },
      {
        title: "Providers and state",
        subtitle: "Runtime backing",
        tone: "provider",
        items: ["Spring AI OpenAI", "H2 commerce data", "Local smoke provider"],
      },
    ],
    developer: {
      sourcePath: "examples/real-apps/chat-capabilities-demo",
      dockerfilePath: "examples/real-apps/chat-capabilities-demo/Dockerfile",
      healthEndpoint: "GET /api/demo/health",
      primaryEndpoints: [
        "POST /api/chat/query",
        "POST /api/chat/suggestions",
        "GET /api/chat/conversations",
        "GET /api/demo/readiness",
        "POST /api/demo/stages/{stage}",
        "POST /api/demo/reset",
        "GET /api/runtime/vector-search",
      ],
      localRun: [
        "mvn -pl examples/real-apps/chat-capabilities-demo spring-boot:run",
        "Use OPENAI_ENABLED=true with OpenAI model and embedding variables for live AI.",
        "Use the demo controls API key when calling stage/reset endpoints outside the UI.",
      ],
      envVars: [
        "PORT",
        "OPENAI_ENABLED",
        "OPENAI_API_KEY",
        "OPENAI_MODEL",
        "OPENAI_EMBEDDING_MODEL",
        "OPENAI_EMBEDDING_DIMENSIONS",
        "AI_DATA_SYNC_ENABLED",
        "APP_ADMIN_API_KEY",
        "CORS_ALLOWED_ORIGINS",
      ],
      codeHotspots: [
        "web/ChatController.java",
        "web/CommerceModeResolver.java",
        "demo/web/DemoController.java",
        "catalog/domain/Product.java",
        "policies/domain/Policy.java",
        "cart/action/AddToCartActionHandler.java",
        "cart/action/CheckoutCartActionHandler.java",
      ],
    },
    dependencies: [
      "Spring Boot Web, Data JPA, Validation, Actuator, OpenAPI, H2, and Lombok.",
      "smoke-support for deployment metadata and no-key smoke checks.",
    ],
    modules: [
      "ai-fabric-starter",
      "ai-fabric-curated-commerce",
      "ai-fabric-provider-spring-ai",
      "ai-fabric-chat-session",
      "ai-fabric-data-sync",
      "ai-fabric-governance",
      "ai-fabric-indexing",
      "ai-fabric-rag",
      "ai-fabric-vector-lucene",
    ],
    aiSurface: [
      "Product, Policy, and Review are @AICapable with @AISearchable and @AIContext fields.",
      "ProductService, PolicyService, and ReviewService use @AIProcess for index synchronization.",
      "Local @AIAction handlers cover catalog, cart, checkout, orders, support, returns, reviews, addresses, shipments, and account lookup.",
    ],
    providers: [
      "OpenAI through ai-fabric-provider-spring-ai for live LLM and embeddings.",
      "Lucene vector retrieval and H2 commerce/chat-session storage.",
      "Local ChatLocalLlmProvider for no-key smoke runs.",
    ],
    flow: [
      "The UI posts chat turns to /api/chat/query with the selected commerce position.",
      "CommerceModeResolver maps UI position to AI Fabric orchestration mode and prompt overlay.",
      "AI Fabric loads chat memory, resolves intent, retrieves staged RAG evidence, and selects local actions when needed.",
      "Write actions return confirmation before execution; domain writes re-enter indexing through @AIProcess.",
    ],
  },
  accountResolver: {
    title: "AI Fabric Account Resolver backend",
    status: "Live backend-backed demo",
    tone: "live",
    backendApp: "examples/real-apps/ai-fabric-account-resolver",
    publicBackend: "https://ai-fabric-account-resolver.46.224.145.148.sslip.io",
    uiRoutes: ["/demos/ai-fabric-account-resolver"],
    summary:
      "A current-account resolver where AI Fabric reads factual profile state, retrieves policy evidence, explains blockers, and proposes governed account actions.",
    diagram: [
      {
        title: "Resolver UI",
        subtitle: "Session-scoped personas",
        tone: "ui",
        items: ["Scenario queue", "Natural chat", "Confirmation cards"],
      },
      {
        title: "Account API",
        subtitle: "Spring Boot app",
        tone: "api",
        items: ["/api/subscriptions/query", "/api/account-resolver/demo/sessions", "/api/account-resolver/users/{userId}/readiness"],
      },
      {
        title: "AI Fabric resolver",
        subtitle: "Iterative orchestration",
        tone: "framework",
        items: ["Chat-session memory", "Current-account target guard", "Action facts and policies"],
      },
      {
        title: "Actions and RAG",
        subtitle: "Governed resolution",
        tone: "rag",
        items: ["get_account_profile", "Payment, address, refund, plan actions", "Policy and plan vector lookup"],
      },
      {
        title: "Providers and state",
        subtitle: "Live backend",
        tone: "provider",
        items: ["Spring AI OpenAI", "Lucene policy vectors", "H2 session users"],
      },
    ],
    developer: {
      sourcePath: "examples/real-apps/ai-fabric-account-resolver",
      dockerfilePath: "examples/real-apps/ai-fabric-account-resolver/Dockerfile",
      healthEndpoint: "GET /api/account-resolver/health",
      primaryEndpoints: [
        "POST /api/subscriptions/query",
        "POST /api/account-resolver/demo/sessions",
        "GET /api/account-resolver/policies",
        "GET /api/account-resolver/users/{userId}/readiness",
        "POST /api/account-resolver/subscriptions/{subscriptionId}/payment-method",
        "POST /api/account-resolver/subscriptions/{subscriptionId}/refund",
        "POST /api/demo/indexing/reindex/plans",
      ],
      localRun: [
        "mvn -pl examples/real-apps/ai-fabric-account-resolver spring-boot:run",
        "Run with OPENAI_ENABLED=true for live natural-language orchestration.",
        "Use /api/account-resolver/demo/sessions to isolate browser sessions before testing writes.",
      ],
      envVars: [
        "PORT",
        "OPENAI_ENABLED",
        "OPENAI_API_KEY",
        "OPENAI_MODEL",
        "OPENAI_EMBEDDING_MODEL",
        "OPENAI_EMBEDDING_DIMENSIONS",
        "CORS_ALLOWED_ORIGINS",
      ],
      codeHotspots: [
        "controller/NaturalLanguageController.java",
        "controller/AccountResolverController.java",
        "service/AccountResolutionService.java",
        "action/handler/GetAccountProfileActionHandler.java",
        "action/handler/UpdatePaymentMethodActionHandler.java",
        "action/handler/RequestRefundActionHandler.java",
        "ai/ResolverAccountOwnedTargetResolutionStep.java",
      ],
    },
    dependencies: [
      "Spring Boot Web, Data JPA, Validation, Actuator, H2/PostgreSQL drivers, and Lombok.",
      "smoke-support for build metadata and release smoke support.",
    ],
    modules: [
      "ai-fabric-starter",
      "ai-fabric-provider-spring-ai",
      "ai-fabric-chat-session",
      "ai-fabric-rag",
      "ai-fabric-vector-lucene",
      "ai-fabric-behavior",
      "ai-fabric-relationship-query",
    ],
    aiSurface: [
      "SubscriptionPlan and Subscription are @AICapable; account-resolution policies are config-driven.",
      "PaymentMethod, Address, and RefundRequest expose AI context fields used in action results.",
      "@AIAction handlers expose get_account_profile, payment/address updates, refunds, plan changes, cancellation, and subscribe.",
      "get_account_profile exposes @ActionFacts so blocker reasoning comes from account facts plus policies.",
    ],
    providers: [
      "OpenAI through ai-fabric-provider-spring-ai for live natural-language orchestration.",
      "Deterministic simple embeddings for account policy and plan retrieval.",
      "Lucene vector search over account-resolution-policy and subscription-plan; H2 stores session-scoped personas.",
    ],
    flow: [
      "The UI posts natural language to /api/subscriptions/query with a stable conversation id.",
      "AI Fabric resolver mode loads chat memory and can run get_account_profile with policy RAG in parallel.",
      "The LLM explains blockers from profile facts and retrieved policies.",
      "Action handlers enforce @ActionAllowed, create @ActionConfirmation cards, and execute writes through @ActionExecute.",
    ],
  },
  behaviorSignals: {
    title: "AI Fabric Behavior Signals backend",
    status: "Live backend-backed demo",
    tone: "live",
    backendApp: "examples/real-apps/behavior-churn-signals",
    publicBackend: "https://behavior-churn-signals.46.224.145.148.sslip.io",
    uiRoutes: ["/demos/ai-fabric-behavior-signals", "/demos/ai-fabric-behavior-signals/agentic-ui"],
    summary:
      "A behavior analytics runtime that submits raw app events to a durable, read-only AI Fabric specialist and turns its validated insight into operator recommendations and an LLM-selected user home preview.",
    diagram: [
      {
        title: "Behavior UI",
        subtitle: "Operator and home preview",
        tone: "ui",
        items: ["Scenario sessions", "Raw event recording", "Agentic UI preview"],
      },
      {
        title: "Behavior API",
        subtitle: "Session-owned workflow",
        tone: "api",
        items: ["Record /events", "Submit app or scheduled /analyses", "Poll /analyses/{invocationId}"],
      },
      {
        title: "Facts and state",
        subtitle: "Application-owned storage",
        tone: "storage",
        items: ["DbExternalEventProvider", "Raw AppBehaviorEvent rows", "Previous approved insight + new events"],
      },
      {
        title: "AI Fabric specialist",
        subtitle: "Durable read-only execution",
        tone: "framework",
        items: ["behavior-risk-analyst@1 manifest", "Lease, retry, and idempotent replay", "Typed insight validation and projection"],
      },
      {
        title: "LLM and presentation",
        subtitle: "Visible, allowlisted output",
        tone: "provider",
        items: ["Spring AI OpenAI", "No automatic writes or hidden fallback", "Allowlisted component-name plan"],
      },
    ],
    developer: {
      sourcePath: "examples/real-apps/behavior-churn-signals",
      dockerfilePath: "examples/real-apps/behavior-churn-signals/Dockerfile",
      healthEndpoint: "GET /api/demo/health",
      primaryEndpoints: [
        "GET /api/demo/health",
        "POST /api/behavior-demo/sessions",
        "GET /api/behavior-demo/dashboard",
        "POST /api/behavior-demo/scenarios/{userId}/events",
        "POST /api/behavior-demo/scenarios/{userId}/analyses",
        "POST /api/behavior-demo/scenarios/{userId}/scheduled-analyses",
        "GET /api/behavior-demo/analyses/{invocationId}",
        "GET /api/behavior-demo/analyses",
        "DELETE /api/behavior-demo/analyses/{invocationId}",
        "POST /api/behavior-demo/scenarios/{userId}/agentic-ui",
      ],
      localRun: [
        "mvn -f examples/real-apps/pom.xml -pl behavior-churn-signals -am package",
        "java -jar examples/real-apps/behavior-churn-signals/target/behavior-churn-signals-1.0.0-SNAPSHOT.jar",
        "Use /api/behavior-demo/sessions to clone isolated demo users per browser session.",
      ],
      envVars: [
        "PORT",
        "AI_LLM_PROVIDER",
        "OPENAI_ENABLED",
        "OPENAI_API_KEY",
        "OPENAI_MODEL",
        "APP_BEHAVIOR_DEMO_REQUIRE_REAL_AI",
        "APP_DATABASE_URL",
        "AI_EXECUTION_ASYNC_ENCRYPTION_SECRET",
        "AI_EXECUTION_ASYNC_FINGERPRINT_SECRET",
        "CORS_ALLOWED_ORIGINS",
      ],
      codeHotspots: [
        "web/BehaviorDemoController.java",
        "web/BehaviorHealthContributor.java",
        "service/DurableBehaviorAnalysisService.java",
        "spi/DbExternalEventProvider.java",
        "service/AgenticUiComposerService.java",
        "ai-specialists/behavior-risk-analyst.yml",
      ],
    },
    dependencies: [
      "Spring Boot Web, Data JPA, Validation, Actuator, H2, and Lombok.",
      "smoke-support for shared health and deployment metadata.",
    ],
    modules: ["ai-fabric-provider-starter", "ai-fabric-provider-spring-ai", "ai-fabric-behavior", "ai-fabric-execution"],
    aiSurface: [
      "No @AICapable entities by design; behavior analytics is fed through the ExternalEventProvider SPI.",
      "AppBehaviorEvent stores raw app events and DbExternalEventProvider exposes them to AI Fabric behavior analysis.",
      "behavior-risk-analyst@1 receives the previous approved insight plus only the raw events added since that insight.",
      "DurableAIExecutionGateway owns queued execution, leases, retry/recovery, cancellation, and idempotent replay.",
      "The app persists each execution source and reconstructs the matching SERVICE/APPLICATION or SYSTEM/SCHEDULED trust boundary while polling and recovery run.",
      "AgenticUiComposerService asks the configured LLM for allowlisted component names and reasons only.",
    ],
    providers: [
      "OpenAI through ai-fabric-provider-spring-ai for live public insight generation.",
      "Deterministic behavior-local provider for local/no-key runs.",
      "No vector DB; H2 stores events, BehaviorInsights, app job bindings, and encrypted durable specialist state.",
    ],
    flow: [
      "The UI creates an isolated browser session and clones seeded behavior scenarios.",
      "Recording an event stores application facts only; it does not silently invoke analysis.",
      "Run analysis submits behavior-risk-analyst@1 with an idempotency key, then polls an opaque invocation id.",
      "The host-scheduled path submits the same typed specialist under a SYSTEM principal and derives its replay key from the exact event batch; the browser supplies neither identity nor idempotency authority.",
      "AI Fabric validates typed sentiment, churn, trend, recommendation, action family, and evidence before projecting one approved insight.",
      "The analytics page exposes recommendations without automatic writes or fallback output; failures stay visible.",
      "Agentic UI receives a validated component-name plan and renders trusted backend-populated props.",
    ],
    operationalProofs: [
      "AI Fabric durable execution state and the app-owned analysis job are stored in JDBC; queued work can be recovered after process restart when the database and execution secrets remain stable.",
      "The app job stores the exact previous insight, new-event batch, execution source, and invocation binding used for projection.",
      "Duplicate delivery of the same outstanding scheduled event batch resolves to the same invocation; after projection, new facts produce a new backend-derived key.",
      "Insight projection is applied once per app job. Provider side effects are not claimed as exactly once.",
    ],
  },
  tenantGuard: {
    title: "AI Fabric Tenant Guard backend",
    status: "Live backend-backed demo",
    tone: "live",
    backendApp: "examples/real-apps/tenant-knowledge-portal",
    publicBackend: "https://ai-fabric-tenant-guard.46.224.145.148.sslip.io",
    uiRoutes: ["/demos/ai-fabric-tenant-guard"],
    summary:
      "A tenant-boundary proof that combines AI Fabric metadata-filtered vector retrieval, LLM-generated cited answers, NL action orchestration, role-aware catalog visibility, session-isolated mutation, and tenant deletion evidence.",
    diagram: [
      {
        title: "Tenant Guard UI",
        subtitle: "Boundary and RAG proof",
        tone: "ui",
        items: ["AI Fabric indexed retrieval", "Tenant search comparison", "Guarded write and deletion evidence"],
      },
      {
        title: "Demo API",
        subtitle: "Spring Boot app",
        tone: "api",
        items: ["/api/tenant-guard-demo/query", "/api/tenant-guard-demo/actions/nl", "/api/tenant-guard-demo/index/proof"],
      },
      {
        title: "AI Fabric runtime",
        subtitle: "Search, generation, orchestration",
        tone: "framework",
        items: ["AICoreService.performSearch", "generateContent for answers/actions", "app-side fail-closed verification"],
      },
      {
        title: "RAG and indexing",
        subtitle: "Tenant document evidence",
        tone: "rag",
        items: ["KnowledgeDocument rows", "tenantId visibility", "visibleToUser metadata"],
      },
      {
        title: "Provider and cleanup",
        subtitle: "Lucene vector index",
        tone: "provider",
        items: ["metadata-filtered Lucene search", "session-scoped vectors", "delete removes document and vector evidence"],
      },
    ],
    developer: {
      sourcePath: "examples/real-apps/tenant-knowledge-portal",
      dockerfilePath: "examples/real-apps/tenant-knowledge-portal/Dockerfile",
      healthEndpoint: "GET /api/demo/health",
      primaryEndpoints: [
        "GET /api/demo/health",
        "GET /api/tenant-guard-demo/dashboard",
        "POST /api/tenant-guard-demo/reset",
        "POST /api/tenant-guard-demo/query",
        "POST /api/tenant-guard-demo/actions/nl",
        "POST /api/tenant-guard-demo/index/seed",
        "GET /api/tenant-guard-demo/index/proof",
        "GET /api/tenant-guard-demo/compare",
        "POST /api/tenant-guard-demo/actions/execute",
        "POST /api/tenant-guard-demo/tenants/delete",
        "GET /api/tenant-knowledge/search",
        "GET /api/tenant-knowledge/catalog",
      ],
      localRun: [
        "mvn -pl examples/real-apps/tenant-knowledge-portal spring-boot:run",
        "Use /query and /index/proof to prove AI Fabric metadata-filtered retrieval.",
        "Use /actions/nl to prove LLM action resolution remains governed by backend policy.",
        "Pass sessionId to isolate browser mutations while testing write/delete paths.",
        "Use the smoke provider locally, or OpenAI-compatible provider settings when testing live embeddings.",
      ],
      envVars: ["PORT", "CORS_ALLOWED_ORIGINS", "AI_LLM_PROVIDER", "AI_EMBEDDING_PROVIDER", "AI_VECTOR_DB_TYPE", "VECTOR_INDEX_PATH"],
      codeHotspots: [
        "web/TenantGuardDemoController.java",
        "web/TenantKnowledgeController.java",
        "service/TenantKnowledgeService.java",
        "src/main/resources/application.yml",
      ],
    },
    dependencies: [
      "Spring Boot Web, Actuator, and Lombok.",
      "smoke-support for shared build metadata.",
    ],
    modules: ["ai-fabric-starter", "ai-fabric-governance", "ai-fabric-vector-lucene"],
    aiSurface: [
      "Explicit KnowledgeDocument records are indexed into AI Fabric vector storage with tenantId, sessionId, visibility, and visibleToUser metadata.",
      "AI Fabric semantic search runs with exact metadata filters before the app performs a second fail-closed boundary check.",
      "RAG answers are generated through AICoreService after retrieval; the LLM receives only verified tenant-safe evidence.",
      "Natural-language actions are resolved through AICoreService with JSON output, then executed only through the backend tenant/role/confirmation policy engine.",
      "ActionAccessMode models read/write access so role and confirmation decisions are explicit.",
      "BoundaryProof is produced by the backend so the UI does not infer tenant policy outcomes.",
    ],
    providers: [
      "Smoke/local provider ids through configuration for no-key local runs.",
      "Lucene vector provider by default with provider diagnostics exposed in /index/proof.",
      "Browser-session scoped document maps and vector metadata prevent one visitor's delete action from changing another visitor's proof state.",
      "Tenant deletion removes matching document rows and their indexed vector entities.",
    ],
    flow: [
      "The UI loads /api/demo/health and /api/tenant-guard-demo/dashboard?sessionId=... for deployed proof state.",
      "/index/seed stores the session's documents as tenant-document vectors with sessionId, tenantId, visibility, and visibleToUser metadata.",
      "/query builds an AI Fabric search request with session and tenant filters, verifies returned evidence, then sends only those hits to the LLM answer generator.",
      "/actions/nl asks the LLM for a JSON action draft, then validates target tenant, role, registered action, and confirmation before any approval.",
      "/compare runs the same query as tenant A, tenant B, and platform admin.",
      "/actions/execute validates target tenant, role, access mode, and confirmation.",
      "/tenants/delete deletes only the requested tenant documents and vector ids, then returns remaining index proof.",
    ],
  },
  privacyShield: {
    title: "AI Fabric Privacy Shield backend",
    status: "Ready-to-deploy backend-backed demo",
    tone: "live",
    backendApp: "examples/real-apps/privacy-first-customer-facing-support",
    publicBackend: "https://ai-fabric-privacy-shield.46.224.145.148.sslip.io",
    uiRoutes: ["/demos/ai-fabric-privacy-shield"],
    summary:
      "A privacy-first support intake that sends sensitive customer text through AI Fabric PII detection before persistence and indexing, then exposes only processed records, detection evidence, and sanitized search proof to the public UI.",
    diagram: [
      {
        title: "Privacy Shield UI",
        subtitle: "Session-scoped support console",
        tone: "ui",
        items: ["Sensitive sample intake", "Redacted record proof", "Safe index search"],
      },
      {
        title: "Privacy demo API",
        subtitle: "Spring Boot app",
        tone: "api",
        items: ["/api/privacy-demo/sessions", "/api/privacy-demo/messages", "/api/privacy-demo/search"],
      },
      {
        title: "AI Fabric privacy",
        subtitle: "Detection and redaction",
        tone: "guard",
        items: ["PIIDetectionService.detectAndProcess", "redaction fallback for detect-only results", "raw payload withheld from public API"],
      },
      {
        title: "Safe indexing",
        subtitle: "Support-message vectors",
        tone: "rag",
        items: ["@AICapable SupportMessage", "processed subject/message only", "query sanitized before vector retrieval"],
      },
      {
        title: "State and health",
        subtitle: "Deployable runtime",
        tone: "provider",
        items: ["H2 support records", "Lucene vector index", "smoke-support /api/demo/health build metadata"],
      },
    ],
    developer: {
      sourcePath: "examples/real-apps/privacy-first-customer-facing-support",
      dockerfilePath: "examples/real-apps/privacy-first-customer-facing-support/Dockerfile",
      healthEndpoint: "GET /api/demo/health",
      primaryEndpoints: [
        "POST /api/privacy-demo/sessions",
        "GET /api/privacy-demo/dashboard",
        "GET /api/privacy-demo/samples",
        "POST /api/privacy-demo/messages",
        "GET /api/privacy-demo/search",
        "POST /api/support/messages",
        "GET /api/support/privacy/customers/{customerId}/inventory",
        "POST /api/support/privacy/customers/{customerId}/delete",
      ],
      localRun: [
        "mvn -B -V --no-transfer-progress -f examples/real-apps/pom.xml -pl privacy-first-customer-facing-support -am spring-boot:run",
        "Open /api/privacy-demo/sessions to create isolated seeded records.",
        "Use /api/privacy-demo/search with a sensitive query to verify the processed query is returned and raw query is not indexed.",
      ],
      envVars: [
        "PORT",
        "CORS_ALLOWED_ORIGINS",
        "AI_PII_MODE",
        "AI_PII_STORE_ENCRYPTED_ORIGINAL",
        "AI_PII_ENCRYPTION_SECRET",
        "JAVA_OPTS",
      ],
      codeHotspots: [
        "service/SupportMessageService.java",
        "service/PrivacyDemoService.java",
        "web/PrivacyDemoController.java",
        "web/PrivacyGovernanceController.java",
        "domain/SupportMessage.java",
        "ai/PrivacySimpleEmbeddingProvider.java",
        "src/main/resources/ai-entity-config.yml",
      ],
    },
    dependencies: [
      "Spring Boot Web, Data JPA, Validation, Actuator, H2, and Lombok.",
      "smoke-support for build metadata and no-key deployment health.",
    ],
    modules: ["ai-fabric-starter", "ai-fabric-governance", "ai-fabric-vector-lucene"],
    aiSurface: [
      "SupportMessage is indexed as support-message with processedSubject, processedMessage, channel, and customer metadata.",
      "SupportMessageService calls PIIDetectionService before saving or indexing any support text.",
      "PrivacyDemoService scopes public demo records with session-prefixed customer IDs and maps records to redacted DTOs.",
      "Semantic search runs PIIDetectionService over the query before AICoreService.performSearch.",
    ],
    providers: [
      "Local PrivacySimpleEmbeddingProvider for no-key embeddings.",
      "Lucene vector search for support-message retrieval.",
      "H2 stores processed support records and governance evidence.",
      "No external LLM required for this demo; the framework capability under test is privacy and safe indexing.",
    ],
    flow: [
      "The UI creates or resets a browser session through /api/privacy-demo/sessions.",
      "The backend seeds support messages using customer IDs prefixed by the session id.",
      "Submitting text calls SupportMessageService.create, which redacts subject/message through AI Fabric PII detection.",
      "Only processed fields, detection count, detection summary, mode, and original-evidence policy return to the public UI.",
      "Search calls /api/privacy-demo/search; the backend redacts the query before AI Fabric vector retrieval and filters results to the current session.",
      "Governance endpoints can inventory or delete privacy-safe customer records when testing developer flows.",
    ],
  },
  smartFaq: {
    title: "Smart FAQ Assistant backend candidate",
    status: "UI page exists; backend not wired live yet",
    tone: "candidate",
    backendApp: "examples/real-apps/smart-faq-assistant",
    uiRoutes: ["/demos/smart-faq-assistant"],
    summary:
      "The current page is explanatory/static. The runnable backend candidate is a config-driven FAQ RAG service with semantic search, optional answer generation, and golden-question quality gates.",
    dependencies: [
      "Spring Boot Web, Data JPA, Validation, Actuator, H2, and Lombok.",
      "smoke-support for release smoke and build metadata.",
    ],
    modules: ["ai-fabric-starter", "ai-fabric-rag", "ai-fabric-vector-lucene"],
    aiSurface: [
      "No Java AI annotations; ai-entity-config.yml defines faq-article searchable fields, embeddable fields, and metadata.",
      "FaqArticleService owns seed, reindex, semantic search, and optional ask flow.",
      "FaqQualityService verifies expected source evidence before claiming RAG quality.",
    ],
    providers: [
      "Deterministic SimpleHashEmbeddingProvider.",
      "Lucene vector search and H2 article storage.",
      "Optional answer generation when an LLM provider is configured.",
    ],
    flow: [
      "Seed FAQ articles through /api/demo/seed.",
      "Reindex articles into the faq-article vector space.",
      "Search delegates to AICoreService.performSearch.",
      "Golden-question runs verify retrieved evidence ids.",
    ],
  },
  documentHub: {
    title: "Document Intelligence Hub backend candidate",
    status: "UI page exists; backend not wired live yet",
    tone: "candidate",
    backendApp: "examples/real-apps/document-ingestion-workbench",
    uiRoutes: ["/demos/document-intelligence-hub"],
    summary:
      "The current page is explanatory/static. The runnable backend candidate accepts trusted text/JSON documents, previews chunks, indexes them through AI Fabric, and deletes stale vector evidence.",
    dependencies: [
      "Spring Boot Web, Data JPA, Validation, Actuator, H2, and Lombok.",
      "Spring AI commons for document-reader integration.",
      "smoke-support for release smoke and build metadata.",
    ],
    modules: ["ai-fabric-starter", "ai-fabric-indexing", "ai-fabric-vector-lucene"],
    aiSurface: [
      "No Java AI annotations; ai-entity-config.yml defines generated kb chunk payloads and metadata.",
      "DocumentSource stores trusted source files.",
      "DocumentChunkManifest records generated chunks so replacement/delete can remove stale vectors.",
    ],
    providers: [
      "Configured embedding provider with Lucene vector DB by default.",
      "Deterministic local providers in smoke mode.",
      "H2 stores source and chunk manifests; trusted-root constrains filesystem reads.",
    ],
    flow: [
      "Create or update a source through /api/documents/sources.",
      "Preview chunks before indexing.",
      "Index normalized chunk payloads with source/chunk metadata.",
      "Re-upload and delete queue stale vector deletes before exposing new evidence.",
    ],
  },
  productDiscovery: {
    title: "Product Discovery backend status",
    status: "Concept page; live coverage is in Shopping",
    tone: "concept",
    backendApp: "Covered by examples/real-apps/chat-capabilities-demo",
    uiRoutes: ["/demos/product-discovery-engine", "/demos/ai-shopping-experience"],
    summary:
      "This page is a product-discovery concept page. The live product search, comparison, cart, coupon, and product RAG proof is implemented in the AI Shopping Experience backend.",
    dependencies: ["No dedicated Product Discovery backend app is wired to this route today."],
    modules: [
      "Live equivalent uses ai-fabric-rag",
      "Live equivalent uses ai-fabric-indexing",
      "Live equivalent uses ai-fabric-vector-lucene",
      "Live equivalent uses ai-fabric-curated-commerce",
    ],
    aiSurface: [
      "The live shopping backend has Product @AICapable fields and @AIAction handlers for search, list, details, cart, and checkout.",
    ],
    providers: [
      "Use the AI Shopping Experience for OpenAI-backed product discovery and Lucene retrieval.",
    ],
    flow: [
      "Concept route demonstrates UX shape only.",
      "For real AI Fabric behavior, run the Shopping demo staged RAG flow and product/cart actions.",
    ],
  },
  codeSearch: {
    title: "Code Documentation Search backend status",
    status: "Concept page only",
    tone: "concept",
    backendApp: "No dedicated real-app backend in this repo yet",
    uiRoutes: ["/demos/code-documentation-search"],
    summary:
      "This page illustrates a code-search use case, but there is no deployed backend app or framework proof wired to it yet.",
    dependencies: ["No backend dependencies are currently attached to this UI route."],
    modules: [
      "Likely future modules: ai-fabric-indexing",
      "Likely future modules: ai-fabric-rag",
      "Likely future modules: ai-fabric-vector-lucene or another vector provider",
    ],
    aiSurface: [
      "A future backend should define code document chunks, repository metadata, language tags, and source references as indexed evidence.",
    ],
    providers: ["No live provider is configured for this route today."],
    flow: [
      "Current page runs mock UI interactions.",
      "Future live flow should ingest code/docs, index chunks, retrieve source-backed evidence, and answer with citations.",
    ],
  },
  meetingNotes: {
    title: "Meeting Notes Analyzer backend status",
    status: "Concept page only",
    tone: "concept",
    backendApp: "No dedicated real-app backend in this repo yet",
    uiRoutes: ["/demos/meeting-notes-analyzer"],
    summary:
      "This page illustrates a meeting-analysis use case, but there is no deployed backend app or framework proof wired to it yet.",
    dependencies: ["No backend dependencies are currently attached to this UI route."],
    modules: [
      "Likely future modules: ai-fabric-provider-spring-ai",
      "Likely future modules: ai-fabric-indexing",
      "Likely future modules: ai-fabric-rag",
    ],
    aiSurface: [
      "A future backend should model transcript chunks, decisions, action items, speakers, and meeting metadata as trusted evidence.",
    ],
    providers: ["No live provider is configured for this route today."],
    flow: [
      "Current page runs mock UI interactions.",
      "Future live flow should ingest notes, extract structured actions, index summaries, and answer from meeting evidence.",
    ],
  },
} satisfies Record<string, DemoBackendArchitectureConfig>;
